version: '3'

services:
  mysql:
    image: mysql
    container_name: container-sql
    volumes:
      - C:/data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    expose:
      - "3306"
    networks:
      microservices-network:
        ipv4_address: 192.168.100.15

  labo_discovery-service:
    build: ./Discovery-Service
    container_name: labo_discovery_service
    ports:
      - "8761:8761"
    expose:
      - "8761"
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 4
    networks:
      microservices-network:
        ipv4_address: 192.168.100.10

  labo_config_service:
    build: ./Configuration-Service
    container_name: labo_config_service
    ports:
      - "9999:9999"
    expose:
      - "9999"
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://192.168.100.10:8761/eureka
    networks:
      microservices-network:
        ipv4_address: 192.168.100.20  # Assign the static IP here
    depends_on:
      labo_discovery-service:
        condition: service_healthy
  labo_gateway_service:
    build: ./Gateway-service
    container_name: labo_gateway_service
    ports:
      - "8888:8888"
    expose:
      - "8888"
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://192.168.100.10:8761/eureka
    depends_on:
      labo_discovery-service:
        condition: service_healthy
  labo_enseignant_service:
    build: ./Enseignant-Service
    container_name: labo_enseignant_service
    ports:
      - "8081:8081"
    expose:
      - "8081"
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://192.168.100.10:8761/eureka
      - CONFIG_SERVICE_URL=http://192.168.100.20:9999
    depends_on:
      labo_discovery-service:
        condition: service_healthy

  labo_chercheur_service:
    build: ./Chercheur-Service
    container_name: labo_chercheur_service
    ports:
      - "8082:8082"
    expose:
      - "8082"
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8082/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://192.168.100.10:8761/eureka
      - CONFIG_SERVICE_URL=http://192.168.100.20:9999
    depends_on:
      labo_discovery-service:
        condition: service_healthy
  labo_projet_service:
    build: ./Projet-Service
    container_name: labo_projet_service
    ports:
      - "8083:8083"
    expose:
      - "8083"
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8083/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://192.168.100.10:8761/eureka
      - CONFIG_SERVICE_URL=http://192.168.100.20:9999
    depends_on:
      labo_discovery-service:
        condition: service_healthy

  labo_security_service:
    build: ./Security_Microservice
    container_name: labo_security_service
    ports:
      - "8787:8787"
    expose:
      - "8787"
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8787/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://192.168.100.10:8761/eureka
      - CONFIG_SERVICE_URL=http://192.168.100.20:9999
    networks:
      microservices-network:
        ipv4_address: 192.168.100.25
    depends_on:
      labo_discovery-service:
        condition: service_healthy


networks:
  microservices-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24